[1mdiff --git a/mtaafix-backend/backend/.gitignore b/mtaafix-backend/backend/.gitignore[m
[1mindex 667aaef..fb9e55a 100644[m
[1m--- a/mtaafix-backend/backend/.gitignore[m
[1m+++ b/mtaafix-backend/backend/.gitignore[m
[36m@@ -31,3 +31,4 @@[m [mbuild/[m
 [m
 ### VS Code ###[m
 .vscode/[m
[32m+[m[32mmtaafix-backend/backend/src/main/resources/application.properties[m
\ No newline at end of file[m
[1mdiff --git a/mtaafix-backend/backend/pom.xml b/mtaafix-backend/backend/pom.xml[m
[1mindex da6b337..165c35b 100644[m
[1m--- a/mtaafix-backend/backend/pom.xml[m
[1m+++ b/mtaafix-backend/backend/pom.xml[m
[36m@@ -8,7 +8,7 @@[m
 		<version>4.1.0</version>[m
 		<relativePath/> <!-- lookup parent from repository -->[m
 	</parent>[m
[31m-	<groupId>com.MtaaFix</groupId>[m
[32m+[m	[32m<groupId>com.mtaafix</groupId>[m
 	<artifactId>backend</artifactId>[m
 	<version>0.0.1-SNAPSHOT</version>[m
 	<name/>[m
[36m@@ -68,6 +68,25 @@[m
 			<scope>test</scope>[m
 		</dependency>[m
 		<dependency>[m
[32m+[m[32m    <groupId>io.jsonwebtoken</groupId>[m
[32m+[m[32m    <artifactId>jjwt-api</artifactId>[m
[32m+[m[32m    <version>0.12.6</version>[m
[32m+[m[32m</dependency>[m
[32m+[m
[32m+[m[32m<dependency>[m
[32m+[m[32m    <groupId>io.jsonwebtoken</groupId>[m
[32m+[m[32m    <artifactId>jjwt-impl</artifactId>[m
[32m+[m[32m    <version>0.12.6</version>[m
[32m+[m[32m    <scope>runtime</scope>[m
[32m+[m[32m</dependency>[m
[32m+[m
[32m+[m[32m<dependency>[m
[32m+[m[32m    <groupId>io.jsonwebtoken</groupId>[m
[32m+[m[32m    <artifactId>jjwt-jackson</artifactId>[m
[32m+[m[32m    <version>0.12.6</version>[m
[32m+[m[32m    <scope>runtime</scope>[m
[32m+[m[32m</dependency>[m
[32m+[m		[32m<dependency>[m
 			<groupId>org.springframework.boot</groupId>[m
 			<artifactId>spring-boot-starter-validation-test</artifactId>[m
 			<scope>test</scope>[m
[1mdiff --git a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/BackendApplication.java b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/BackendApplication.java[m
[1mindex f217461..4e62b59 100644[m
[1m--- a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/BackendApplication.java[m
[1m+++ b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/BackendApplication.java[m
[36m@@ -1,4 +1,4 @@[m
[31m-package com.MtaaFix.backend;[m
[32m+[m[32mpackage com.mtaafix.backend;[m
 [m
 import org.springframework.boot.SpringApplication;[m
 import org.springframework.boot.autoconfigure.SpringBootApplication;[m
[1mdiff --git a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/AuthController.java b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/AuthController.java[m
[1mnew file mode 100644[m
[1mindex 0000000..ba512ba[m
[1m--- /dev/null[m
[1m+++ b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/AuthController.java[m
[36m@@ -0,0 +1,22 @@[m
[32m+[m[32mpackage com.mtaafix.backend.auth;[m
[32m+[m
[32m+[m[32mimport lombok.RequiredArgsConstructor;[m
[32m+[m[32mimport org.springframework.web.bind.annotation.*;[m
[32m+[m
[32m+[m[32m@RestController[m
[32m+[m[32m@RequestMapping("/auth")[m
[32m+[m[32m@RequiredArgsConstructor[m
[32m+[m[32mpublic class AuthController {[m
[32m+[m
[32m+[m[32m    private final AuthService authService;[m
[32m+[m
[32m+[m[32m    @PostMapping("/register")[m
[32m+[m[32m    public String register(@RequestBody RegisterRequest request) {[m
[32m+[m[32m        return authService.register(request);[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    @PostMapping("/login")[m
[32m+[m[32m    public String login(@RequestBody LoginRequest request) {[m
[32m+[m[32m        return authService.login(request);[m
[32m+[m[32m    }[m
[32m+[m[32m}[m
\ No newline at end of file[m
[1mdiff --git a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/AuthService.java b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/AuthService.java[m
[1mnew file mode 100644[m
[1mindex 0000000..2e0d8c5[m
[1m--- /dev/null[m
[1m+++ b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/AuthService.java[m
[36m@@ -0,0 +1,51 @@[m
[32m+[m[32mpackage com.mtaafix.backend.auth;[m
[32m+[m
[32m+[m[32mimport com.mtaafix.backend.security.JwtUtil;[m
[32m+[m[32mimport com.mtaafix.backend.user.User;[m
[32m+[m[32mimport com.mtaafix.backend.user.UserRepository;[m
[32m+[m[32mimport lombok.RequiredArgsConstructor;[m
[32m+[m[32mimport org.springframework.security.crypto.password.PasswordEncoder;[m
[32m+[m[32mimport org.springframework.stereotype.Service;[m
[32m+[m
[32m+[m[32m@Service[m
[32m+[m[32m@RequiredArgsConstructor[m
[32m+[m[32mpublic class AuthService {[m
[32m+[m
[32m+[m[32m    private final UserRepository userRepository;[m
[32m+[m[32m    private final PasswordEncoder passwordEncoder;[m
[32m+[m[32m    private final JwtUtil jwtUtil;[m
[32m+[m
[32m+[m[32m    public String register(RegisterRequest request) {[m
[32m+[m
[32m+[m[32m    if (userRepository.existsByEmail(request.getEmail())) {[m
[32m+[m[32m        return "Email already exists";[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    User user = new User();[m
[32m+[m
[32m+[m[32m    user.setName(request.getName());[m
[32m+[m[32m    user.setEmail(request.getEmail());[m
[32m+[m[32m    user.setPassword(passwordEncoder.encode(request.getPassword()));[m
[32m+[m
[32m+[m[32m    userRepository.save(user);[m
[32m+[m
[32m+[m[32m    return "User registered successfully";[m
[32m+[m[32m}[m
[32m+[m
[32m+[m[32mpublic String login(LoginRequest request) {[m
[32m+[m
[32m+[m[32m    User user = userRepository.findByEmail(request.getEmail())[m
[32m+[m[32m            .orElse(null);[m
[32m+[m
[32m+[m[32m    if (user == null) {[m
[32m+[m[32m        return "User not found";[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    if (!passwordEncoder.matches(request.getPassword(), user.getPassword())) {[m
[32m+[m[32m        return "Invalid password";[m
[32m+[m[32m    }[m
[32m+[m
[32m+[m[32m    return jwtUtil.generateToken(user.getEmail());[m
[32m+[m[32m}[m
[32m+[m
[32m+[m[32m}[m
\ No newline at end of file[m
[1mdiff --git a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/LoginRequest.java b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/LoginRequest.java[m
[1mnew file mode 100644[m
[1mindex 0000000..d77119d[m
[1m--- /dev/null[m
[1m+++ b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/LoginRequest.java[m
[36m@@ -0,0 +1,13 @@[m
[32m+[m[32mpackage com.mtaafix.backend.auth;[m
[32m+[m
[32m+[m[32mimport lombok.Getter;[m
[32m+[m[32mimport lombok.Setter;[m
[32m+[m
[32m+[m[32m@Getter[m
[32m+[m[32m@Setter[m
[32m+[m[32mpublic class LoginRequest {[m
[32m+[m
[32m+[m[32m    private String email;[m
[32m+[m[32m    private String password;[m
[32m+[m
[32m+[m[32m}[m
\ No newline at end of file[m
[1mdiff --git a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/RegisterRequest.java b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/RegisterRequest.java[m
[1mnew file mode 100644[m
[1mindex 0000000..55d817e[m
[1m--- /dev/null[m
[1m+++ b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/auth/RegisterRequest.java[m
[36m@@ -0,0 +1,14 @@[m
[32m+[m[32mpackage com.mtaafix.backend.auth;[m
[32m+[m
[32m+[m[32mimport lombok.Getter;[m
[32m+[m[32mimport lombok.Setter;[m
[32m+[m
[32m+[m[32m@Getter[m
[32m+[m[32m@Setter[m
[32m+[m[32mpublic class RegisterRequest {[m
[32m+[m
[32m+[m[32m    private String name;[m
[32m+[m[32m    private String email;[m
[32m+[m[32m    private String password;[m
[32m+[m
[32m+[m[32m}[m
\ No newline at end of file[m
[1mdiff --git a/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/issue/Issue.java b/mtaafix-backend/backend/src/main/java/com/MtaaFix/backend/issue/Issue.java[m
[1mnew file mo